import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
// code to import Note component
// the './' refers to the current directory (i.e. the 'components' sub-directory of the part2-rendering-collections directory)
import Note from './components/Note'


const App = ({notes}) => {
  return (
    <div>
      <h1>Notes</h1>
      {/* instead of the format below, we can instead iterate through the React elements with the map function */}

      {/* Don't do this
      <ul>
        <li>{notes[0].content}</li>
        <li>{notes[1].content}</li>
        <li>{notes[2].content}</li>
      </ul> */}

      {/* Do this instead */}
      {/* NOTE: each element generated by the map method must have a unique key value labelled via an attribute called "key" */}
      <ul>
        {notes.map(note => 
          <Note key={note.id} note={note}/>
        )}
      </ul>
    </div>
  )
}

export default App
